stages:
  - test
  - build
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.node_template:
  image: node:20
  before_script:
    - cd frontend/
    - npm ci --cache .npm --prefer-offline
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/

sast:
  stage: test

include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml

preview:
  extends: .node_template
  stage: build
  rules:
    - if: $CI_COMMIT_TAG !~ /^v.*$/
  environment:
    name: "preview/$CI_COMMIT_REF_NAME"
    url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/build/index.html"
  variables:
    PUBLIC_URL: "/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/build"
  script:
    - make npm/build
  artifacts:
    paths:
      - build/*
    expire_in: 7 days

publish:
  extends: .node_template
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*$/
  script:
    - make npm/build
  artifacts:
    paths:
      - build/*
    expire_in: 1 day

pages:
  image: alpine
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*$/
  script:
    - rm -r public/
    - mv build/ public/
  artifacts:
    paths:
      - public/
